#!/bin/bash

SCRIPT_PATH=""

pauseAnyKey() {
	read -n 1 -s -r -p 'Press any key to continue...'
	echo
}

setScriptPath() {
	SCRIPT_PATH="`dirname \"$0\"`"
	SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"
	if [ -z "$SCRIPT_PATH" ]; then
		[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
	fi
}

checkScriptPermission() {
	if [[ $EUID -ne 0 ]]; then
		echo 'You must be a root user!'
		[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
	fi
}

rebootRequired() {
	echo '';
	read -p 'Reboot? [Y/n] ' -n 1 -r
	echo '';
	if [[ ! $REPLY =~ ^[Nn]$ ]]; then
		reboot
	fi
}

changeHostname() {
	echo '';
	echo 'Allowed: a-z 0-9 - (Hyphen)';
	echo 'No capitalization! For example: dev-your-name';
	read -p 'Change Hostname: ' -r
	echo '';
	if [[ $REPLY != '' ]]; then
		hostnamectl set-hostname ${REPLY}
		echo "127.0.0.1    ${REPLY}" >> /etc/hosts
	fi
}

generateSshKey() {
	echo '';
	echo 'Generate SSH key';
	read -p 'Your e-mail address: ' -r
	echo '';
	if [[ $REPLY != '' ]]; then
		ssh-keygen -t rsa -b 4096 -C "${REPLY}" -f /home/user/.ssh/id_rsa
		chown -R user:user /home/user/.ssh
	fi
}

changeDevelopmentContext() {
	echo '';
	read -p 'Your Development Context (Username): ' -r
	echo '';
	if [[ $REPLY != '' ]]; then
		echo "TYPO3_CONTEXT=Development/${REPLY}" >> /etc/environment
		echo "FLOW_CONTEXT=Development/${REPLY}" >> /etc/environment
		echo "WWW_CONTEXT=Development/${REPLY}" >> /etc/environment

		echo "Your full development context is: Development/${REPLY}"
		pauseAnyKey
	fi
}

convertSshKeyToPutty() {
	puttygen /home/user/.ssh/id_rsa -o /home/user/.ssh/id_rsa.ppk
	chown user:user /home/user/.ssh/id_rsa.ppk
	echo 'Putty SSH key stored here: /home/user/.ssh/id_rsa.ppk';
	pauseAnyKey
}

configureGit() {
	echo '';
	echo 'Configure Git';

	read -p 'Your full name (firstname lastname): ' -r
	echo '';
	if [[ $REPLY != '' ]]; then
		runuser -l user -c "git config --global user.name \"${REPLY}\""
	fi

	read -p 'Your e-mail address: ' -r
	echo '';
	if [[ $REPLY != '' ]]; then
		runuser -l user -c "git config --global user.email \"${REPLY}\""
	fi
}

configureDockerGlobal() {
	git clone https://github.com/pluswerk/docker-global.git /home/user/projects/docker-global
	cd /home/user/projects/docker-global && docker-compose up -d && cd ${SCRIPT}
}

menu() {
	echo ''
	echo '1) Change hostname'
	echo '3) Generate SSH key'
	echo '3) Convert SSH key to Putty key'
	echo '4) Configure Git'
	echo '5) Change development context'
	echo '6) Install docker-global'
	echo '7) Change keyboard layout'
	echo '8) Reboot'
	echo '0) Exit'
	read -p 'Enter your choice: ' choice

	case "$choice" in
		'1')
			changeHostname
		;;
		'2')
			generateSshKey
		;;
		'3')
			convertSshKeyToPutty
		;;
		'4')
			configureGit
		;;
		'5')
			changeDevelopmentContext
		;;
		'6')
			configureDockerGlobal
		;;
		'7')
			dpkg-reconfigure keyboard-configuration
		;;
		'8')
			rebootRequired
		;;

		'0')
			exit 0
		;;
		*)
			echo 'Wrong choice... Please try again.'
			menu
		;;
	esac
}

# Run script
setScriptPath
checkScriptPermission
menu
